### ISSUE TITLE
View strategy shows binary sensors for sync state

### ISSUE THREAD

**Issue by chelming** [raman325/lock_code_manager#115]
### What happened?

The binary sensors were switched to sensors but the sensors still show up on my view strategy. Is this the expected behavior because of how the switch happened? Should I just redo the configuration?

### Steps to reproduce the issue

1. Install pre 0.4.0
2. Add view using the strategy 
3. Upgrade to 0.4.1

### Home Assistant Version

2024.3.3

### What version of Lock Code Manager are you running?

0.4.1

### Lock make and model

Yale qssure

**Comment by raman325** [comment]
go to the config entry for your configuration and then click on entities. You will see some listed there that can be deleted (the old sensor ones). They will be removed from the UI. Good feedback though, I should make it so that doesn't break the UI
