### ISSUE TITLE
[ISSUE] When HA restarts, frontend needs a refresh to show the UI

### ISSUE THREAD

**Issue by raman325** [raman325/lock_code_manager#119]
### What happened?

Frontend can't recover from an HA restart by itself

### Steps to reproduce the issue

1. Load the Lock Code Manager view or dashboard.
2. Restart HA while staying on this page
3. Observe that after HA starts, an error is shown
...

### Home Assistant Version

n/a

### What version of Lock Code Manager are you running?

n/a

**Comment by chelming** [comment]
is it this message or is this something different?
> ERROR: No Lock Code Manager configuration called Home found!

**Comment by raman325** [comment]
Yeah. Does a restart fix it?

**Comment by chelming** [comment]
nope, but clearing data on my phone did. I'm going to assume it was a cache issue.

**Comment by raman325** [comment]
sorry meant a reload
