### ISSUE TITLE
ISSUE: Unable to install via HACS

### ISSUE THREAD

**Issue by tykeal** [raman325/lock_code_manager#17]
**Describe the bug**
I added this integration to HACS as a custom repository (since it's not available in HACS yet despite the docs) When I try to install the integration I get an **unknown error**

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: VM (kvm)
- Home Assistant version: 2024.2.2
- Hassio/Docker/Core? Hassio
- Component version: N/A
- Lock integration name: Virtual (yes, I know, ZWave only but I'm just trying to install it!)
- Lock make and model: Virtual

**Logs**
The only logs I'm getting even though it says to check logs for details, there's no extra details!

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 990, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
```

**Additional context**
Trying to get a feel for what this offers over Keymaster so I can determine how / if I should support it as a lock manager for my Rental Control integration.

**Comment by tykeal** [comment]
I'm going to do a manual install without HACS for now but wanted to call out that it's having an issue with HACS. Maybe because you don't have any releases yet?

**Comment by tykeal** [comment]
No issues installing manually.

**Comment by chelming** [comment]
seeing the same. I think cutting a release would solve it since that's how HACS knows there's an update.

**Comment by raman325** [comment]
yes this is missing a release. I want to finish all my bug testing before I push an actual release and advertise this a little more widely

**Comment by chelming** [comment]
If you're interested in letting people test you could do a beta release and check "This is a pre-release." This would force users to select seeing beta releases and it wouldn't show up with the normal releases.

E.g., https://github.com/home-assistant/core/releases/tag/2024.2.0b11

**Comment by raman325** [comment]
Already pushed it as a non beta release so it should be installable now
