### ISSUE TITLE
Support Virtual locks

### ISSUE THREAD

**Issue by tykeal** [raman325/lock_code_manager#18]
**Is your feature request related to a problem? Please describe.**
I would like to do some development work using this integration as a potential dependency of my own integration [Rental Control](https://github.com/tykeal/homeassistant-rental-control). My test instance does not have a ZWave controller at all, even though I do install one of the ZWave addons.

I instead use the **`Virtual Components`** integration from HACS to have a lock that I can define for Keymaster and my own Rental Control to target (though Keymaster complains bitterly about not being able to find Zwave for good reason)

**Describe the solution you'd like**
I would like to be able to select Virtual locks (**`lock.virtual_<lock_name>`**) as a target to allow me to inspect and play with the UI even if it doesn't function 100%

**Describe alternatives you've considered**
If I had the funds and resources I would add a zwave controller to my test instance along with a real lock, but I don't really.

**NOTE:** I'm well aware that this really is a nice to have for development development work and if it's outside of what you want to support go ahead and just close this request.

**Comment by raman325** [comment]
@tykeal does my suggestion make sense? I don't see the value of adding this to the integration but I am open to being convinced. If you agree though, can you close this?

**Comment by tykeal** [comment]
@raman325 I'll admit the request is rather self-serving on my part so that I don't have to have zwave locks attached to my test instance and not in service somewhere. Since I decided to finally get a zwave stick for my test instance and have an old zwave lock I can't use because of mechanical issues not zwave issues, I think I'm fine for now.

**Comment by raman325** [comment]
on second thought, I see the value in having a fake lock to play with. I don't think virtual locks are the solution though because there's no service for setting or clearing user codes. Instead I'd recommend that we create something like the mock lock class I have put into tests.

**Comment by tykeal** [comment]
Well, that just sounds like a feature request for the virtual lock component ;) but happy that you've seen that this is a good idea after all :D means I may not have to source a second zwave lock to do child / parent testing when I get RC able to use this as an alternative to using Keymaster for lock management ;)

**Comment by tykeal** [comment]
I just raised https://github.com/twrecked/hass-virtual/issues/100 around this.

**Comment by raman325** [comment]
I thought about this some more, we don't actually need the services, we can manage code slot state in the integration by persisting it in files in `config/.storage`

Do you want to give https://github.com/raman325/lock_code_manager/pull/103 a shot

**Comment by tykeal** [comment]
Sorry, I haven't had a chance to try. I'll do so ASAP
