### ISSUE TITLE
[Feature Request] Keep it modular / don't duplicate functionality of home assistant

### ISSUE THREAD

**Issue by bagobones** [raman325/lock_code_manager#20]
**Is your feature request related to a problem? Please describe.**
I am currently using keymaster and for the life of me don't understand why it has certain features that are essentially standard automations like the door sensors and auto lock. These should be kept out of the main "lock manager"
I would very much like a lock code manager that JUST provides lock code management, and unique features to lock code management.

**Describe the solution you'd like**
- Sync codes / name codes between locks
- Add history / log book events with the codes NICE NAME in them "House sitter", "Janes code" so I know who unlocked the door
- Timed / calendar dependent codes
- maybe provide blueprints for the semi redundant stuff or separate it as a second addon if implemented to keep the code management clean

**Comment by raman325** [comment]
Don't worry, we are on the same page: https://github.com/raman325/lock_code_manager/wiki/Why-is-'x'-not-supported%3F-Will-it-be-supported-in-the-future%3F

**Comment by bagobones** [comment]
Are there plans to make a custom card vs how keymaster does copy and past of a pile of entities?

**Comment by raman325** [comment]
It already does, see the README
