### ISSUE TITLE
[Question] Where to get the lock-code-manager card for dashboards?

### ISSUE THREAD

**Issue by fxfitz** [raman325/lock_code_manager#257]
### What happened?

Trying to follow this: https://github.com/raman325/lock_code_manager/wiki/Add-a-UI-for-lock-code-management

However, I apparently don't have the lovelace lock-code-manager card after installing the Lock Code Manager Integration (after importing this repo in HACS).

Help?

TIA!

### Steps to reproduce the issue

1. Import lock_code_manager via HACS
2. Add new Lock Code Manager integration in HA
3. Configure Lock Code Manager [via yaml in the integration UI]
4. Attempt to create a dashboard following instructions on Wiki

### Home Assistant Version

2024.6.3

### What version of Lock Code Manager are you running?

0.5.1

**Comment by uSlackr** [comment]
Install it separately from HACS.

\\Greg

________________________________
From: Fran Fitzpatrick ***@***.***>
Sent: Tuesday, June 18, 2024 6:34:43 AM
To: raman325/lock_code_manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [raman325/lock_code_manager] [Question] Where to get the lock-code-manager card for dashboards? (Issue #257)


What happened?

Trying to follow this: https://github.com/raman325/lock_code_manager/wiki/Add-a-UI-for-lock-code-management

However, I apparently don't have the lovelace lock-code-manager card after installing the Lock Code Manager Integration (after importing this repo in HACS).

Help?

TIA!

Steps to reproduce the issue

  1.  Import lock_code_manager via HACS
  2.  Add new Lock Code Manager integration in HA
  3.  Configure Lock Code Manager [via yaml in the integration UI]
  4.  Attempt to create a dashboard following instructions on Wiki

Home Assistant Version

2024.6.3

What version of Lock Code Manager are you running?

0.5.1

Lock make and model

No response

Relevant log output

No response

Screenshots

No response

Anything else?

No response

**Comment by fxfitz** [comment]
Derp. I tried that, but didn't see any frontend components. I readded the custom repository, and then it showed up.

Software is weird sometimes. :-P

Thanks!
