### ISSUE TITLE
[Feature Request] Option to make PINs visible in the generated UI

### ISSUE THREAD

**Issue by tykeal** [raman325/lock_code_manager#45]
Currently the only way to find out what PIN is assigned to a slot is to inspect the lock via ZWaveJS-UI _or_ the diagnostic that is added to the lock (note this does not seem to always stay in sync!)

It would be nice to have an option in the UI to display the PIN instead of always being hidden. Perhaps a toggle just below the PIN field for **Show / Hide PIN** that defaults to off.

**Comment by chelming** [comment]
is this fixed-ish? it seems that text.code_slot_1_pin exists and can display it now?

**Comment by raman325** [comment]
the concern I believ eis what shows in the UI. The state of the entity is not hidden, and if you click on the entity itself to pop up the modal, you should see the value. Is this sufficient or do you think the UI should have this capability? I wonder if this is more of a feature request upstream to have a "show" icon on password fields

**Comment by tykeal** [comment]
Personally, I'm the only one that accesses anything that displays PINs and I need fairly easy access to the defined PIN when I'm informing my STR guests what their door code is. I don't really want to have to click around too much, especially since I'm regularly having to copy the current PIN when I'm using my phone and not at my computer.

Keymaster has a config option to hide pins or not hide pins for the generate dashboard. So, maybe a similar option. would be good?

**Comment by tykeal** [comment]
I'll also note that while I can _see_ it in the modal popup in the history graph, assuming it's been on long enough, there's no way to copy it.

**Comment by chelming** [comment]
You can copy from the modal that appears when you click the code slot sensor

**Comment by tykeal** [comment]
I can't, because my modal pops up with the slot sensor still as a password display

**Comment by chelming** [comment]
Oh, interesting. My keymaster integration is that way but my lock code manager has a seensor that isn't set to mode: password.

**Comment by tykeal** [comment]
There's a diagnostic sensor that is getting created by LCM that is visible, but it's not on the generated dashboard. I suppose I could cobble something up personally that uses that, but it's not really the point of my feature request here ;)

**Comment by chelming** [comment]
I'm getting it on the generated dashboard if I set `include_code_slot_sensors: true` in the stategy

**Comment by chelming** [comment]
E.g., 
![image](https://github.com/raman325/lock_code_manager/assets/7746625/49b6eb34-16b4-46c1-8462-69babe938c4f)

**Comment by chelming** [comment]
obviously "fake" has an actual number in it and has been redacted for the screenshot 😅

**Comment by tykeal** [comment]
Ah, I do have that. Looks like I overlooked it since it was below the fold. Nevermind, I can close this. It's fine with that then.
