### ISSUE TITLE
[Feature Request] Ability to remove a device

### ISSUE THREAD

**Issue by chelming** [raman325/lock_code_manager#61]
### Problem Description

I set up a second lock in the same config entry as my first lock but I don't see a way to remove it. When I go to the device I only have the option to "remove from zwave." Deleting the entity from the configuration doesn't seem to remove it.

### Feature Description

An ability to open a device and "remove from lock code manager"

**Comment by raman325** [comment]
have you tried going through the options flow? Settings > Devices & Services > Lock Code Manager

click on the entry then click on configure. At the top you can add and remove locks

**Comment by chelming** [comment]
Yep, when I do that the device sticks around.

**Comment by chelming** [comment]
![image](https://github.com/raman325/lock_code_manager/assets/7746625/d86a58be-2acc-4f8f-94a7-2de724b85850)
![image](https://github.com/raman325/lock_code_manager/assets/7746625/c2a46bf6-abc3-4a76-9d5c-698d57435dd6)

**Comment by raman325** [comment]
do you see the code sensors when you click on the device you removed?

**Comment by chelming** [comment]
sensors disappear, just not the device
