### ISSUE TITLE
[ISSUE] Changing PIN on active slot does not update the code

### ISSUE THREAD

**Issue by tykeal** [raman325/lock_code_manager#63]
### What happened?

A PIN code being changed when the slot is already enabled and in sync does not push the new code

### Steps to reproduce the issue

1. Configure a code slot with a valid code and enable it
2. Wait for the slot show synced
3. Validate that the code really has been synced to the lock (check via ZWave-JS UI or something)
4. Change the PIN
5. Notice that the logbook will log the PIN change, but the code is never pushed to the lock
6. Notice that the code slot sensor never updates
7. Disable slot and wait for the slot to properly sync
8. Enable slot and wait for the slot to sync
9. Notice that the slot is now using the new code

### Home Assistant Version

2024.2.5

### What version of Lock Code Manager are you running?

0.2.5 (commit fb4fec39bc43f0cbcb80397a71922e83e31ee7ff, current HEAD at time of report)

### Lock make and model

Kwikset 910

**Comment by raman325** [comment]
good call I forgot to track this entity, easy fix
