### ISSUE TITLE
[Feature Request] Switch from binary sensor to sensor

### ISSUE THREAD

**Issue by raman325** [raman325/lock_code_manager#74]
### Feature Description

Sensor can have one of four states:
1. Disabled
2. Disabling
3. Enabled
4. Enabling

or something of that sort

### Anything else?

not sure if this is all that useful or not, need to think about it

**Comment by chelming** [comment]
for which component?

**Comment by tykeal** [comment]
@raman325 is this for the PIN sync sensor or a different sensor that I'm failing to identify? It would definitely be nice it it have more than `on` and `off` states.

For instance, I haven't raised a bug about it yet, but I noticed that if you change a PIN for a slot that has already been synced out the `PIN synced to locks` sensor never goes to off. Even though I would expect it to switch to `off` right away and then back to `on` after the PIN was updated. I would hope that this enhancement would take care of that.

I can see the following state transitions:

```mermaid
flowchart LR
    Empty[Sync: Disabled -- currently 'off'
    PIN: unset
    Enabled: false]

    Enabled[Sync: Enabled -- currently 'on'
    PIN: set
    Enabled: true]

    Disabled[Sync: Disabled -- currently 'off'
    PIN: set
    Enabled: false]

    DisabledWithPIN[Sync: Disabled -- currently 'off'
    PIN: unset
    Enabled: true]

    Empty -- PIN set, enabled: true, sync: Enabling --> Enabled
    Enabled -- enabled: false, sync: disabling --> Disabled
    Enabled -- PIN changed, sync: enabling --> Enabled
    Enabled -- PIN removed, sync disabling --> DisabledWithPIN
    DisabledWithPIN -- enabled: false --> Empty
    Disabled -- PIN removed --> Empty
```

**Comment by tykeal** [comment]
I realized that the above diagram is sorta hard to read. I've would update it to be this:

```mermaid
flowchart LR
    Empty[Sync: Disabled -- currently 'off'
    PIN: unset
    Enabled: false]

    Enabled[Sync: Enabled -- currently 'on'
    PIN: set
    Enabled: true]

    Disabled[Sync: Disabled -- currently 'off'
    PIN: set
    Enabled: false]

    DisabledByPIN[Sync: Disabled -- currently 'off'
    PIN: unset
    Enabled: true]

    Empty <-- PIN changed or removed --> Disabled
    Empty <-- Enabled: changed --> DisabledByPIN
    Enabled -- enabled: false, sync: disabling --> Disabled
    Enabled -- PIN changed, sync: enabling --> Enabled
    Enabled -- PIN removed, sync disabling --> DisabledByPIN
    DisabledByPIN -- PIN added, sync: enabling --> Enabled
    Disabled -- enabled: true, sync: enabling --> Enabled
```

It's a bit easier to understand what I think the states should be. The 'Empty' state is effectively the unconfigured state and initial configuration would essentially follow two edges at once if the slot is set with a PIN and enabled at the same time. It's a little hard to show with mermaid and make the diagram clean :-/

**Comment by tykeal** [comment]
Either way works. You're dealing either with a true / false and 2 sensors or string comparison and one sensor when doing tests.

Personally I think the single sensor with a finite state is better than having to deal with 2 sensors in all of the potential combinatorial states. It does, however, mean it's easier to typo things when doing checks if using a string based state.

**Comment by chelming** [comment]
> single sensor with a finite state is better than having to deal with 2 sensors in all of the potential combinatorial states.

that's a solid point. comparing one sensor vs 4 combinations (on on, on off, off on, off off) feels simpler.

**Comment by raman325** [comment]
while it is slightly easier to create a template based off of one sensor rather than two, I don't think it's as clean of a solution since the possible state combinations are the same, and there are two different aspects of keeping the PIN in sync (whether it is considered active or not and whether that decision is reflected in the lock). While I want to keep the user experience as simple as possible, I also want to keep the integration as simple as possible to future proof it.

I am going to move forward with the two binary sensor solution and will revaluate in the future if needed

**Comment by tykeal** [comment]
That works too.
