### ISSUE TITLE
Unable to set usercode starting with a zero

### ISSUE THREAD

**Issue by pdobrien3** [raman325/lock_code_manager#75]
### What happened?

Successfully setup the integration but noticed that even number slots (2, 4 and 6) were not synced.  The `code_slot_#_pin` showed the correct pin.  On further investigation, code slots 2, 4 and 6 all started with a zero.  Unknown if it is related.

### Steps to reproduce the issue

1.
2.
3.
...

### Home Assistant Version

2024.3.0b6

### What version of Lock Code Manager are you running?

0.3.1

### Lock make and model

Kwikset 916 zwave

### Relevant log output

```shell
Logger: homeassistant.util.logging
Source: util/logging.py:102
First occurred: 4:52:35 AM (3 occurrences)
Last logged: 4:52:35 AM

Exception in _add_keys_to_track when dispatching 'lock_code_manager_redacted_add_tracking_2': ({'enabled': False, 'name': False, 'pin': False, 'pin_used': False},) Traceback (most recent call last): File "/config/custom_components/lock_code_manager/binary_sensor.py", line 299, in _add_keys_to_track await self._update_state() File "/config/custom_components/lock_code_manager/binary_sensor.py", line 266, in _update_state await self.async_update_usercodes(states) File "/config/custom_components/lock_code_manager/binary_sensor.py", line 128, in async_update_usercodes await lock.async_set_usercode( File "/config/custom_components/lock_code_manager/providers/zwave_js.py", line 178, in async_set_usercode await self.async_call_service( File "/config/custom_components/lock_code_manager/providers/_base.py", line 217, in async_call_service raise err File "/config/custom_components/lock_code_manager/providers/_base.py", line 210, in async_call_service await self.hass.services.async_call( File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call response_data = await coro ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service return await target(service_call) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call single_response = await _handle_entity_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call result = await task ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/zwave_js/lock.py", line 166, in async_set_lock_usercode await set_usercode(self.info.node, code_slot, usercode) File "/usr/local/lib/python3.12/site-packages/zwave_js_server/util/lock.py", line 145, in set_usercode raise ValueError("User code must be at least 4 digits") ValueError: User code must be at least 4 digits
```

### Anything else?

slots 4 and 6 have the exact same error message

**Comment by pdobrien3** [comment]
I just went to look at my yaml config and noticed the leading zeros were missing.  Once I added them, HAss started generating multiple system/repairs for lock_code_manager

**Comment by raman325** [comment]
when you say that you looked at your yaml config, do you mean that you clicked on the Configure button and looked at the slots YAML data? Or did you look at the yaml some other way?

**Comment by pdobrien3** [comment]
sorry, yes, in the integration configuration

**Comment by pdobrien3** [comment]
I followed the wiki (https://github.com/raman325/lock_code_manager/wiki/Configuration-Structure), which does not have quotes, just an FYI.  I did use yaml during the initial setup.  I just went back and looked at the config and it had double quotes around the number.  I tried to use single quotes and it started generating all kinds of system/repairs again

**Comment by pdobrien3** [comment]
I added the leading 0 one at a time and hit submit.  after all three were added without errors I restarted hass and it seems to be working.  The system/repair errors looked like they were happening every couple seconds and i didnt pay much attention to them, bad on my part...They looked pretty empty actually.

**Comment by raman325** [comment]
OK so should we close this?

**Comment by pdobrien3** [comment]
yes, thank you
